server {
    listen 80;
    resolver 127.0.0.11 ipv6=off valid=10s;

    location /api/v1/feed {
        set $read_api http://read-api:3001;
        proxy_pass $read_api/feed$is_args$args;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/v1/posts {
        set $write_api http://write-api:3002;
        proxy_pass $write_api/posts;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/v1/debug/seed {
        set $write_api http://write-api:3002;
        proxy_pass $write_api/debug/seed$is_args$args;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /media/ {
        set $minio_api http://minio:9000;
        proxy_pass $minio_api/media/;
    }
}
